FROM nginx
WORKDIR /server
COPY ./nginx.conf /etc/nginx/nginx.conf
COPY ./start.sh /server
COPY ./default.conf /etc/nginx/conf.d/default.conf
RUN chmod 777 /server/start.sh
EXPOSE 8080
CMD /server/start.sh && sleep infinity
